# Generated by Django 3.2.4 on 2021-06-10 03:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Shard',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, verbose_name="Shard's id")),
                ('name', models.CharField(max_length=50, verbose_name="Shard's name")),
                ('thumbnail_url', models.URLField(verbose_name="Shard's thumbnail")),
                ('pak_url', models.URLField(verbose_name="Shard's URL")),
            ],
            options={
                'verbose_name': 'Shard',
                'verbose_name_plural': 'Shards',
            },
        ),
        migrations.CreateModel(
            name='ShardList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'Shard List',
                'verbose_name_plural': 'Shard Lists',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, verbose_name="User's id")),
                ('name', models.CharField(max_length=50, verbose_name="User's name")),
                ('bookmarked_lists', models.ManyToManyField(to='alleyways.ShardList', verbose_name='Bookmarked shard lists')),
                ('bookmarked_shards', models.ManyToManyField(to='alleyways.Shard', verbose_name='Bookmarked shards')),
                ('following_users', models.ManyToManyField(to='alleyways.User', verbose_name='Following users')),
            ],
            options={
                'verbose_name': 'User',
                'verbose_name_plural': 'Users',
            },
        ),
        migrations.AddField(
            model_name='shardlist',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='alleyways.user', verbose_name='Shard List Author'),
        ),
        migrations.AddField(
            model_name='shardlist',
            name='shard',
            field=models.ManyToManyField(to='alleyways.Shard', verbose_name='shard'),
        ),
        migrations.AddField(
            model_name='shard',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='alleyways.user', verbose_name='Author'),
        ),
    ]
