# Generated by Django 3.2.4 on 2021-06-10 03:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alleyways', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='bookmarked_lists',
            field=models.ManyToManyField(blank=True, to='alleyways.ShardList', verbose_name='Bookmarked shard lists'),
        ),
        migrations.AlterField(
            model_name='user',
            name='bookmarked_shards',
            field=models.ManyToManyField(blank=True, to='alleyways.Shard', verbose_name='Bookmarked shards'),
        ),
        migrations.AlterField(
            model_name='user',
            name='following_users',
            field=models.ManyToManyField(blank=True, to='alleyways.User', verbose_name='Following users'),
        ),
    ]
