# Generated by Django 3.2.4 on 2021-06-10 03:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alleyways', '0002_auto_20210610_0348'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
