# Generated by Django 3.2.4 on 2021-06-10 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alleyways', '0003_alter_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shard',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
